import tensorflow as tf
import os
from django.conf import settings
import numpy as np
from tensorflow.keras.models import load_model # type: ignore
from tensorflow.keras.preprocessing import image # type: ignore

model = load_model(os.path.join(settings.BASE_DIR, "model_efficientnet.keras"))
breed = ['Chihuahua',
 'Japanese_spaniel',
 'Maltese_dog',
 'Pekinese',
 'Shih',
 'Blenheim_spaniel',
 'papillon',
 'toy_terrier',
 'Rhodesian_ridgeback',
 'Afghan_hound',
 'basset',
 'beagle',
 'bloodhound',
 'bluetick',
 'black',
 'Walker_hound',
 'English_foxhound',
 'redbone',
 'borzoi',
 'Irish_wolfhound',
 'Italian_greyhound',
 'whippet',
 'Ibizan_hound',
 'Norwegian_elkhound',
 'otterhound',
 'Saluki',
 'Scottish_deerhound',
 'Weimaraner',
 'Staffordshire_bullterrier',
 'American_Staffordshire_terrier',
 'Bedlington_terrier',
 'Border_terrier',
 'Kerry_blue_terrier',
 'Irish_terrier',
 'Norfolk_terrier',
 'Norwich_terrier',
 'Yorkshire_terrier',
 'wire',
 'Lakeland_terrier',
 'Sealyham_terrier',
 'Airedale',
 'cairn',
 'Australian_terrier',
 'Dandie_Dinmont',
 'Boston_bull',
 'miniature_schnauzer',
 'giant_schnauzer',
 'standard_schnauzer',
 'Scotch_terrier',
 'Tibetan_terrier',
 'silky_terrier',
 'soft',
 'West_Highland_white_terrier',
 'Lhasa',
 'flat',
 'curly',
 'golden_retriever',
 'Labrador_retriever',
 'Chesapeake_Bay_retriever',
 'German_short',
 'vizsla',
 'English_setter',
 'Irish_setter',
 'Gordon_setter',
 'Brittany_spaniel',
 'clumber',
 'English_springer',
 'Welsh_springer_spaniel',
 'cocker_spaniel',
 'Sussex_spaniel',
 'Irish_water_spaniel',
 'kuvasz',
 'schipperke',
 'groenendael',
 'malinois',
 'briard',
 'kelpie',
 'komondor',
 'Old_English_sheepdog',
 'Shetland_sheepdog',
 'collie',
 'Border_collie',
 'Bouvier_des_Flandres',
 'Rottweiler',
 'German_shepherd',
 'Doberman',
 'miniature_pinscher',
 'Greater_Swiss_Mountain_dog',
 'Bernese_mountain_dog',
 'Appenzeller',
 'EntleBucher',
 'boxer',
 'bull_mastiff',
 'Tibetan_mastiff',
 'French_bulldog',
 'Great_Dane',
 'Saint_Bernard',
 'Eskimo_dog',
 'malamute',
 'Siberian_husky',
 'affenpinscher',
 'basenji',
 'pug',
 'Leonberg',
 'Newfoundland',
 'Great_Pyrenees',
 'Samoyed',
 'Pomeranian',
 'chow',
 'keeshond',
 'Brabancon_griffon',
 'Pembroke',
 'Cardigan',
 'toy_poodle',
 'miniature_poodle',
 'standard_poodle',
 'Mexican_hairless',
 'dingo',
 'dhole',
 'African_hunting_dog']
def predict(path):
    # img = image.load_img("C:\\Users\\user\\Downloads\\dogyy.jpg" ,target_size=(224, 224,3))  # Resize to model's input size
    
    img = image.load_img(path ,target_size=(224, 224,3))  # Resize to model's input size
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)  # Expand to batch dimension
    predictions = model.predict(img_array)[0]
    top_indices = np.argsort(predictions)[-3:][::-1]  # Get top 3 highest probability indices

    top_breeds = [
        {"name": breed[i], "probability": ("%.2f" % (float(100)*float(predictions[i])))} for i in top_indices
    ]

    return top_breeds

    breed_index = breed[np.argmax(predictions)]
    return breed_index
